# Generated by Django 5.1.7 on 2025-06-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
