# Generated by Django 5.1.7 on 2025-05-23 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('buying_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('ltr', 'Liters'), ('m', 'Meters'), ('box', 'Box')], default='pcs', max_length=10)),
                ('min_stock_level', models.PositiveIntegerField(default=5, help_text='Threshold for low stock alert')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('add', 'Addition'), ('remove', 'Removal')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_category_name'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('company', 'name')},
        ),
    ]
