# Generated by Django 5.1.7 on 2025-05-23 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('sales_invoices', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='companies.employee'),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_invoices.sale'),
        ),
        migrations.AddField(
            model_name='employeecommissionsetting',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_settings', to='companies.employee'),
        ),
        migrations.AddField(
            model_name='employeecommissionsetting',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_commissions', to='services.service'),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='companies.employee'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='companies.employee'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeremuneration',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='companies.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='employeecommissionsetting',
            unique_together={('employee', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeremuneration',
            unique_together={('employee', 'remuneration_type')},
        ),
    ]
