# Generated by Django 5.1.7 on 2025-06-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('sales_invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecommission',
            name='sale',
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='sale_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales_invoices.saleitem'),
            preserve_default=False,
        ),
    ]
