# Generated by Django 5.1.7 on 2025-06-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyregistrationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyRegistrationRequest',
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
