# Generated by Django 5.1.7 on 2025-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_delete_companyregistrationrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
