# Generated by Django 5.1.7 on 2025-06-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_employeepayroll_payslip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeremuneration',
            old_name='effective_month',
            new_name='effective_date',
        ),
    ]
